version: '3.1'
services:

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgresDB
    volumes:
      - .:/app
    env_file:
      - ./.envs/local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgresDB:
    image: postgres
    volumes:
      - "/var/lib/postgresql/data"
    env_file:
      - ./.envs/local/.postgres
    ports:
      - "5432:5432"
    container_name: postgresDB

