version: '3.1'

volumes:
  production_postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/local/.postgres
    ports:
      - "5432:5432"

